"""empty message

Revision ID: 8d2bd19f42bd
Revises: 
Create Date: 2019-11-25 17:49:10.848625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2bd19f42bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('shop_order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('payway', sa.String(length=256), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('product_info', sa.String(length=256), nullable=True),
    sa.Column('sign', sa.String(length=256), nullable=False),
    sa.Column('lifetime', sa.Integer(), nullable=True),
    sa.Column('payer_account', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('sign')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
